import fs from 'node:fs';
import assert from 'node:assert/strict';
import {demoSnapshot,demoLength} from './src/demo/demoIncident';
import {generateSummary} from './src/lib/summary';
import {liveIntelligence} from './src/lib/model';
import {createPdfReport,pdfFilename} from './src/lib/pdfSummary';
import mupdf from './tmp/pdf-qa/node_modules/mupdf/dist/mupdf.js';
const font=new Uint8Array(fs.readFileSync('public/fonts/ResQVoiceReport.ttf'));
fs.mkdirSync('output/pdf',{recursive:true});fs.mkdirSync('tmp/pdfs',{recursive:true});
const snapshot=demoSnapshot(demoLength),emptySession={generationId:0,incident:null,events:[],turns:[]};
const full=generateSummary(snapshot.session,snapshot.intelligence,true,new Date('2026-09-09T05:00:00Z'));
const empty=generateSummary(emptySession,liveIntelligence(emptySession),false,new Date('2026-09-09T05:00:00Z'));
const stress=full+'\n## Long-record validation\n\n'+Array.from({length:35},(_,i)=>`- ${i+1}. Action assigned to Zoë García: `+'Validate evidence while retaining uncertainty. '.repeat(12)).join('\n');
for(const [name,report] of [['INC-2047-ResQVoice-Incident-Summary',full],['empty-live',empty],['long-record',stress]]){
 const pdf=createPdfReport(report,name==='empty-live'?undefined:snapshot.session.incident?.id,font);const bytes=new Uint8Array(pdf.output('arraybuffer'));assert.equal(new TextDecoder().decode(bytes.slice(0,5)),'%PDF-');
 fs.writeFileSync(`output/pdf/${name}.pdf`,bytes);const doc=mupdf.Document.openDocument(bytes,'application/pdf');let extracted='';
 for(let i=0;i<doc.countPages();i++){const page=doc.loadPage(i);extracted+=page.toStructuredText('preserve-whitespace').asText();if(name!=='long-record'||i===0||i===doc.countPages()-1)fs.writeFileSync(`tmp/pdfs/${name}-${i+1}.png`,page.toPixmap(mupdf.Matrix.scale(1.1,1.1),mupdf.ColorSpace.DeviceRGB,false).asPNG())}
 const normalized=extracted.replace(/\s+/g,' ');
 assert.ok(normalized.includes('Root cause remains unconfirmed.'));
 assert.ok(normalized.includes('Generated by ResQVoice'));
 if(name==='INC-2047-ResQVoice-Incident-Summary'){for(const title of ['Established Information','Active Hypotheses','Open Questions','Actions','Decisions','Evidence / Corroboration','Contradictions / Disputed Claims','Participants','Duration','DEMO DATA'])assert.ok(normalized.includes(title),title);assert.ok(normalized.includes('19 minutes'));assert.ok(normalized.includes('Recent deployment may be associated'));}
 if(name==='empty-live')assert.ok(!normalized.includes('DEMO DATA'));
 if(name==='long-record'){assert.ok(normalized.includes('35. Action assigned to Zoë García'));assert.ok(doc.countPages()>5)}
 console.log(`PASS ${name}: ${doc.countPages()} pages, ${bytes.length} bytes`);
}
assert.equal(pdfFilename('INC-2047'),'INC-2047-ResQVoice-Incident-Summary.pdf');assert.ok(!pdfFilename('../../x:bad/id').includes('/'));
console.log('PASS PDF signature, content, empty/live isolation, Unicode, pagination and filename sanitization');
