import React from 'react';
Object.assign(globalThis,{React});
﻿import assert from 'node:assert/strict';
import {renderToStaticMarkup} from 'react-dom/server';
import {Overview,IntelligenceWorkspace,ActionsWorkspace,TimelineWorkspace,SummaryWorkspace} from './src/components/Workspaces';
import {VoiceRoom} from './src/components/VoiceRoom';
import {demoSnapshot,demoLength} from './src/demo/demoIncident';
const {session,intelligence:data}=demoSnapshot(demoLength);
const overview=renderToStaticMarkup(<Overview data={data} session={session} navigate={()=>{}}/>);
assert.ok(overview.includes('CURRENT INCIDENT STATE'));
assert.ok(!overview.includes('Incident transcript'));
assert.ok(!overview.includes('Push to talk'));
const voice=renderToStaticMarkup(<VoiceRoom session={session} data={data} demo connection="Local simulation"/>);
assert.ok(voice.includes('Incident transcript'));
assert.ok(voice.includes('Historical dialogue'));
assert.ok(voice.includes('Maya Chen'));
assert.ok(renderToStaticMarkup(<IntelligenceWorkspace data={data}/>).includes('CONTEXT &amp; EVIDENCE'));
assert.ok(renderToStaticMarkup(<ActionsWorkspace data={data}/>).includes('<table>'));
assert.ok(renderToStaticMarkup(<TimelineWorkspace session={session}/>).includes('full-timeline'));
const report=renderToStaticMarkup(<SummaryWorkspace session={session} data={data} demo/>);
for(const text of ['Executive Summary','Incident Details','Participants','Download PDF','Root cause remains unconfirmed.'])assert.ok(report.includes(text),text);
console.log('PASS: separate voice workspace, overview without transcript, intelligence detail, action table, coherent timeline, report preview');
