import { jsPDF } from 'jspdf';
const purple = '#7b39fc', ink = '#2b2344', muted = '#665873', rule = '#e2d9ed';
export function pdfFilename(incidentId?: string) {
    const safe = (incidentId ?? 'incident').normalize('NFKC').replace(/[^a-zA-Z0-9_-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80) || 'incident';
    return `${safe}-ResQVoice-Incident-Summary.pdf`;
}
let fontRequest: Promise<Uint8Array> | undefined;
export function loadReportFont() {
    if (!fontRequest)
        fontRequest = fetch(`${import.meta.env.BASE_URL}fonts/ResQVoiceReport.ttf`).then(response => { if (!response.ok)
            throw new Error('Report font unavailable. Reload and retry.'); return response.arrayBuffer(); }).then(buffer => new Uint8Array(buffer)).catch(error => { fontRequest = undefined; throw error; });
    return fontRequest;
}
function base64(bytes: Uint8Array) { let binary = ''; for (let i = 0; i < bytes.length; i += 8192)
    binary += String.fromCharCode(...bytes.subarray(i, i + 8192)); return btoa(binary); }
/** Renders the exact text shown in the preview. No transcript extraction or inference. */
export function createPdfReport(report: string, incidentId: string | undefined, font: Uint8Array) {
    const pdf = new jsPDF({ unit: 'pt', format: 'a4', compress: true, putOnlyUsedFonts: true });
    pdf.addFileToVFS('ResQVoiceReport.ttf', base64(font));
    pdf.addFont('ResQVoiceReport.ttf', 'ResQVoice', 'normal');
    pdf.setFont('ResQVoice', 'normal');
    pdf.setProperties({ title: `${incidentId ?? 'Incident'} - ResQVoice Incident Summary`, subject: 'Current incident state, evidence and operational record', author: 'ResQVoice', creator: 'ResQVoice' });
    const width = pdf.internal.pageSize.getWidth(), height = pdf.internal.pageSize.getHeight(), left = 44, right = width - 44, bottom = height - 58;
    let y = 88;
    const header = () => { pdf.setFillColor(purple); pdf.rect(left, 30, 26, 4, 'F'); pdf.setFontSize(10); pdf.setTextColor(ink); pdf.text('RESQVOICE / INCIDENT SUMMARY', left, 53); pdf.setFontSize(8); pdf.setTextColor(muted); const id = pdf.splitTextToSize(incidentId ?? 'No active incident', 180); pdf.text(id[0], right, 53, { align: 'right' }); pdf.setDrawColor(rule); pdf.line(left, 65, right, 65); };
    const newPage = () => { pdf.addPage(); header(); y = 88; };
    const ensure = (space: number) => { if (y + space > bottom)
        newPage(); };
    const lines = (text: string, size: number, available: number): string[] => { pdf.setFontSize(size); return pdf.splitTextToSize(text.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g, ''), available); };
    const text = (value: string, { size = 10, indent = 0, color = ink, gap = 5 }: {
        size?: number;
        indent?: number;
        color?: string;
        gap?: number;
    } = {}) => { const wrapped = lines(value, size, right - left - indent), leading = size * 1.5; for (const line of wrapped) {
        ensure(leading);
        pdf.setFontSize(size);
        pdf.setTextColor(color);
        pdf.text(line, left + indent, y);
        y += leading;
    } y += gap; };
    const heading = (value: string) => { const wrapped = lines(value, 13, right - left); ensure(wrapped.length * 20 + 75); y += 11; pdf.setDrawColor(rule); pdf.line(left, y - 8, right, y - 8); text(value, { size: 13, color: purple, gap: 9 }); };
    const metadata = (label: string, value: string) => { const wrapped = lines(value, 10, right - left - 118); for (let i = 0; i < wrapped.length; i++) {
        ensure(17);
        pdf.setFillColor('#faf8fd');
        pdf.rect(left, y - 11, right - left, 17, 'F');
        pdf.setTextColor(muted);
        pdf.setFontSize(9);
        if (i === 0)
            pdf.text(label, left + 8, y);
        pdf.setTextColor(ink);
        pdf.setFontSize(10);
        pdf.text(wrapped[i], left + 118, y);
        y += 17;
    } y += 3; };
    header();
    let section = '';
    const generated = report.match(/## Generated by ResQVoice\n+([^\n]+)/)?.[1] ?? 'Timestamp not recorded';
    for (const line of report.split('\n')) {
        if (!line.trim())
            continue;
        if (line.startsWith('# ')) {
            text('RESQVOICE INCIDENT SUMMARY', { size: 19, gap: 13 });
            continue;
        }
        if (line.startsWith('## ')) {
            section = line.slice(3);
            if (section !== 'Generated by ResQVoice')
                heading(section);
            continue;
        }
        if (section === 'Generated by ResQVoice')
            continue;
        if (line.startsWith('DEMO DATA')) {
            text(line, { size: 10, color: purple, gap: 10 });
            continue;
        }
        if (section === 'Incident Details' && line.includes(': ')) {
            const colon = line.indexOf(': ');
            metadata(line.slice(0, colon), line.slice(colon + 2));
            continue;
        }
        const detail = line.startsWith('  - '), item = line.startsWith('- ');
        // Keep short entries with their first metadata line instead of orphaning a heading.
        if (item)
            ensure(45);
        text(line.replace(/^\s*- /, ''), { size: detail ? 9 : 10, indent: detail ? 14 : item ? 7 : 0, color: detail ? muted : ink, gap: detail ? 6 : 5 });
    }
    const count = pdf.getNumberOfPages();
    for (let page = 1; page <= count; page++) {
        pdf.setPage(page);
        pdf.setDrawColor(rule);
        pdf.line(left, height - 41, right, height - 41);
        pdf.setFontSize(8);
        pdf.setTextColor(muted);
        pdf.text(`Generated by ResQVoice / ${generated}`, left, height - 27);
        pdf.text(`${page} / ${count}`, right, height - 27, { align: 'right' });
    }
    return pdf;
}
