import { emptyIntelligence, normalizeSpeech, observe, type Intelligence } from './intelligence.js'
import { answerStateQuery, answerWithLLM, classifyRoute, type Route } from './qa.js'
import { InterventionManager, evaluateIntervention } from './intervention.js'
export type Status='pending'|'completed'|'cancelled'|'stale-discarded'|'failed'; export type Tool='createIncident'|'updateSeverity'|'notifyTeam'|'getIncidentStatus'|'cancelNotification';
export type Event={id:string;type:'generation_started'|'tool'|'interrupt'|'stale_discarded'|'intelligence';sessionId:string;turnId:string;generationId:number;timestamp:string;status:Status|'completed';latencyMs?:number;tool?:Tool;message:string}
type Incident={id:string;severity:string;title:string;status:string;team:string;startedAt?:string}; type Session={generationId:number;incident:Incident|null;intelligence:Intelligence;events:Event[];turns:any[];controllers:Map<number,AbortController[]>;statusClarification?:{askedAt:string}}
const uid=()=>crypto.randomUUID().slice(0,8),now=()=>new Date().toISOString(),sessions=new Map<string,Session>(),interventionManagers=new Map<string,InterventionManager>();let number=2847;
export const getSession=(id:string)=>{if(!sessions.has(id))sessions.set(id,{generationId:0,incident:null,intelligence:emptyIntelligence(),events:[],turns:[],controllers:new Map});return sessions.get(id)!};
const emit=(s:Session,e:Omit<Event,'id'|'timestamp'>)=>{const x={...e,id:uid(),timestamp:now()};s.events.push(x);return x};const team=(v:string)=>v.match(/\b(backend|payments|platform|on-call)\b/i)?.[1]?.toLowerCase();const priority=(v:string)=>v.match(/\bp([123])\b/i)?.[1]&&`P${v.match(/\bp([123])\b/i)![1]}`;
export function interrupt(sessionId:string,reason='interrupt'){const s=getSession(sessionId),old=s.generationId;s.controllers.get(old)?.forEach(c=>c.abort());for(const e of s.events)if(e.generationId===old&&e.status==='pending')e.status='cancelled';s.generationId++;emit(s,{type:'interrupt',sessionId,turnId:'interrupt',generationId:s.generationId,status:'completed',message:reason});return s}
function statusCommand(text:string,session:Session){if(session.statusClarification&&Date.now()-Date.parse(session.statusClarification.askedAt)>120000)session.statusClarification=undefined;const value=text.trim().toLowerCase();if(/^yes\b/.test(value)&&session.statusClarification){session.statusClarification=undefined;if(session.incident)session.incident.status='Resolved';return 'Incident marked resolved.'}if(/^no\b/.test(value)&&session.statusClarification){session.statusClarification=undefined;return 'The incident remains open.'}if(/\bdo not (?:declare|mark) (?:the )?incident resolved\b|\b(?:mark|resolve) (?:the )?incident resolved\b|^the incident (?:is )?resolved\b/.test(value)){if(session.incident)session.incident.status=/\bdo not (?:declare|mark)/.test(value)?'Investigating':'Resolved';return /\bdo not (?:declare|mark)/.test(value)?'The incident remains open.':'Incident marked resolved.'}return ''}
export async function command(sessionId:string,turnId:string,text:string,delay=3000){const s=getSession(sessionId);interrupt(sessionId,'replacement_command');const generationId=s.generationId,controller=new AbortController();s.controllers.set(generationId,[controller]);s.turns.push({id:turnId,role:'commander',text,timestamp:now(),generation:generationId});emit(s,{type:'generation_started',sessionId,turnId,generationId,status:'completed',message:'New generation'});const p=priority(text),t=team(text),l=text.toLowerCase(),normalized=normalizeSpeech(text),route:Route=classifyRoute(text);let spoken='I did not understand that command.',observation='';const beforeConflicts=s.intelligence.conflicts.length;
if((route==='INCIDENT_STATEMENT'||route==='ACTION'||route==='DECISION')&&l.includes('create')&&p){const title=text.match(/for (.+?)(?: and notify|$)/i)?.[1]??'an incident';s.incident={id:`INC-${number++}`,severity:p,title,status:'Investigating',team:'on-call',startedAt:now()};emit(s,{type:'tool',tool:'createIncident',sessionId,turnId,generationId,status:'completed',message:'Incident created'});spoken=`${p} incident created for ${title}.`}
if((route==='INCIDENT_STATEMENT'||route==='ACTION'||route==='DECISION')&&l.includes('change it to')&&p&&s.incident){s.incident.severity=p;emit(s,{type:'tool',tool:'updateSeverity',sessionId,turnId,generationId,status:'completed',message:`Severity ${p}`});spoken=`Incident changed to ${p}.`}
if((route==='INCIDENT_STATEMENT'||route==='ACTION'||route==='DECISION')&&l.includes('notify')&&t){const start=performance.now(),e=emit(s,{type:'tool',tool:'notifyTeam',sessionId,turnId,generationId,status:'pending',message:`Notifying ${t}`});setTimeout(()=>{if(controller.signal.aborted||generationId!==s.generationId){if(e.status==='pending')e.status='stale-discarded';emit(s,{type:'stale_discarded',tool:'notifyTeam',sessionId,turnId,generationId,status:'stale-discarded',latencyMs:performance.now()-start,message:`${t} fenced`});return}if(e.status==='pending'){e.status='completed';e.latencyMs=performance.now()-start;e.message=`Notified ${t}`;if(s.incident)s.incident.team=t}},delay)}
if(route==='STATUS_CLARIFICATION'){s.statusClarification={askedAt:now()};spoken='Did you mean that the incident is resolved?'}else if(route==='CLARIFICATION_RESPONSE'&&s.statusClarification){spoken=statusCommand(text,s)||'The incident remains open.'}else if(route==='STATUS_COMMAND'){spoken=statusCommand(text,s)||'The incident remains open.'}else if(route==='STATE_QUERY'){observation=answerStateQuery(text,s.intelligence,s.incident?.status??'Investigating')}else if(route==='INCIDENT_ANALYSIS'||route==='GENERAL_KNOWLEDGE'){const approved=evaluateIntervention({transcript:text,intent:route,events:[],incidentState:s.intelligence});if(!approved.shouldSpeak){spoken='';}else {const answer=await answerWithLLM(text,s.intelligence,s.incident,s.turns.slice(-8).map(turn=>({role:turn.role,text:turn.text})),controller.signal,route==='GENERAL_KNOWLEDGE');if(controller.signal.aborted||generationId!==s.generationId)return {session:s,spoken:'',generationId};spoken=answer.answer}}else{observation=observe(s.intelligence,text,turnId,now(),s.incident?.status??'Investigating')}
if((route==='INCIDENT_STATEMENT'||route==='ACTION'||route==='DECISION'||route==='CLARIFICATION_RESPONSE')&&!s.incident&&/(?:checkout|check out|payments?)/i.test(normalized)&&/(?:failures?|errors?|failing|cannot|cant|unable)/i.test(normalized))s.incident={id:`INC-${number++}`,severity:p??'Not recorded',title:'Checkout failures',status:'Investigating',team:'Unassigned',startedAt:now()};
const events:string[]=[];if(s.intelligence.conflicts.length>beforeConflicts)events.push('CONFLICT_DETECTED');if(/(?:deployment).*(?:definitely|certainly|clearly).*(?:caused|root cause)|(?:deployment).*(?:caused the outage|is the root cause)/i.test(normalized)&&s.intelligence.hypotheses.find(h=>h.id==='deployment')?.status!=='confirmed')events.push('ROOT_CAUSE_SAFETY');const manager=interventionManagers.get(sessionId)??new InterventionManager();interventionManagers.set(sessionId,manager);const intervention=manager.decide({transcript:text,intent:route,events,incidentState:s.intelligence});if(events.includes('ROOT_CAUSE_SAFETY'))spoken="That isn't confirmed. Current evidence does not establish the deployment as the root cause.";else if(observation&&intervention.shouldSpeak)spoken=observation;if(!intervention.shouldSpeak)spoken='';emit(s,{type:'intelligence',sessionId,turnId,generationId,status:'completed',message:text});if(spoken.trim())s.turns.push({id:uid(),role:'copilot',text:spoken.trim(),timestamp:now(),generation:generationId});return {session:s,spoken,generationId,intervention}}


