import assert from 'node:assert/strict';
import { command, getSession } from '../server/src/engine.ts';

const id = `state-query-${crypto.randomUUID()}`;
const run = async (text: string) => command(id, crypto.randomUUID(), text);
await run("We're seeing checkout failures above 40%.");
await run('Latency jumped to 900 milliseconds.');
await run('The deployment finished 10 minutes before the spike.');
await run('Database CPU and connection counts look normal.');
await run("Let's investigate the payment gateway.");
await run('Please check the payment service logs.');
await run('I suspect the payment gateway might be causing the failures.');
const root = await run('What caused the outage?');
assert.match(root.spoken, /does not establish a root cause/i);
await run('Errors are also occurring on the previous version.');
await run('Database CPU still looks normal.');
await run('Approve the rollback.');
await run('Checkout errors increased from 40% to 60%.');
await run('We should monitor checkout recovery.');
const known = await run('What do we know?');
const unknown = await run("What don't we know?");
const hypotheses = await run('What hypotheses are active?');
const decreased = await run('Checkout failures dropped from 60% to 12%.');
const proves = await run('Does that prove the deployment caused the outage?');
const status = await run('Is the incident resolved?');
const s = getSession(id), i = s.intelligence;
assert.equal(i.hypotheses.find(item => item.id === 'deployment')?.status, 'disputed');
assert.equal(i.hypotheses.find(item => item.id === 'payment-gateway')?.status, 'unconfirmed');
assert.ok(i.conflicts.length); assert.ok(i.actions.some(item => /investigate.*gateway/i.test(item.text)));
assert.ok(i.actions.some(item => /check.*payment service logs/i.test(item.text)));
assert.ok(i.actions.some(item => /monitor.*checkout recovery/i.test(item.text)));
assert.ok(i.decisions.length); assert.equal(i.facts.find(item => item.originalText === 'Checkout failures dropped from 60% to 12%.')?.metric?.current, 12);
assert.match(known.spoken, /checkout|database|previous version/i); assert.match(unknown.spoken, /unknown|disputed/i);
assert.match(hypotheses.spoken, /deployment|payment-gateway/i); assert.doesNotMatch(proves.spoken, /\bconfirmed\b|definitely caused/i); assert.match(status.spoken, /under investigation/i); assert.match(decreased.spoken, /60.*12/);
assert.equal(i.questions.filter(item => /what do we know|what don't we know|what hypotheses|caused the outage|prove the deployment|incident resolved/i.test(item.originalText ?? '')).length >= 5, true);

const isolated = await command(`isolated-${crypto.randomUUID()}`, crypto.randomUUID(), 'Rollback.');
assert.doesNotMatch(isolated.spoken, /Action recorded: rollback/i);
console.log('PASS: state queries, gateway hypothesis, metrics, lifecycle safety, status query, and action regressions');
