import { useEffect, useRef, useState } from 'react';
import { ThemeToggleBar } from './ThemeToggleBar';
import './hero.css';
const videoUrl = 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260210_031346_d87182fb-b0af-4273-84d1-c6fd17d6bf0f.mp4';
export function EntryHero({ theme, onTheme, onStart, onJoin, onDemo, navigate, connection }: {
    theme: string;
    onTheme: (theme: string) => void;
    onStart: () => void;
    onJoin: () => void;
    onDemo: () => void;
    navigate: (page: string) => void;
    connection: string;
}) {
    const [menu, setMenu] = useState(false), [reduced, setReduced] = useState(() => matchMedia('(prefers-reduced-motion: reduce)').matches), [paused, setPaused] = useState(false), [failed, setFailed] = useState(false);
    const video = useRef<HTMLVideoElement>(null), visual = useRef<HTMLDivElement>(null), menuButton = useRef<HTMLButtonElement>(null), frame = useRef(0);
    useEffect(() => { const media = matchMedia('(prefers-reduced-motion: reduce)'); const change = () => setReduced(media.matches); media.addEventListener('change', change); return () => { media.removeEventListener('change', change); cancelAnimationFrame(frame.current); }; }, []);
    useEffect(() => { if (!menu)
        return; const close = (e: KeyboardEvent) => { if (e.key === 'Escape') {
        setMenu(false);
        menuButton.current?.focus();
    } }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [menu]);
    useEffect(() => { const el = video.current; if (!el)
        return; if (paused || reduced)
        el.pause();
    else
        void el.play().catch(() => setPaused(true)); }, [paused, reduced]);
    const go = (page: string) => { setMenu(false); navigate(page); };
    return <div className="entry-hero relative isolate min-h-screen w-full overflow-hidden"><a className="skip" href="#workspace">Skip to entry content</a><div className="hero-fallback absolute inset-0" aria-hidden="true"/>{!reduced && !failed && <video ref={video} className="absolute inset-0 h-full w-full object-cover" autoPlay loop muted playsInline preload="metadata" aria-hidden="true" tabIndex={-1} onError={() => setFailed(true)}><source src={videoUrl} type="video/mp4"/></video>}
 <header className="hero-navbar relative z-10 mx-auto flex w-full flex-wrap items-center justify-between gap-4 px-5 py-5 lg:px-12"><a className="brand" href="#overview"><span className="brand-mark" aria-hidden="true">R</span><span>ResQ<span className="accent">Voice</span><small>INCIDENT COMMAND CENTER</small></span></a><nav aria-label="Entry navigation" className="hidden items-center gap-7 xl:flex"><button onClick={() => go('voice')}>Live Voice Room</button><button onClick={() => go('intelligence')}>Incident Intelligence</button><button onClick={onDemo}>Demo</button></nav><div className="flex items-center gap-3"><ThemeToggleBar theme={theme} onChange={onTheme}/><button className="hero-primary hidden px-5 py-3 lg:block" onClick={onStart}>Start Incident</button><button ref={menuButton} className="hero-menu-button xl:hidden" aria-expanded={menu} aria-controls="entry-menu" onClick={() => setMenu(!menu)} aria-label={menu ? 'Close navigation menu' : 'Open navigation menu'}>{menu ? 'Close' : 'Menu'} <span aria-hidden="true">{menu ? '×' : '☰'}</span></button></div>{menu && <nav id="entry-menu" aria-label="Mobile entry navigation" className="hero-mobile-menu grid w-full grid-cols-2 gap-2 p-4 xl:hidden">{[['overview', 'Overview'], ['voice', 'Live Voice Room'], ['intelligence', 'Intelligence'], ['actions', 'Actions'], ['timeline', 'Timeline'], ['summary', 'Incident Summary']].map(([id, label]) => <button key={id} onClick={() => go(id)}>{label}</button>)}<button onClick={onDemo}>Run Demo Incident</button></nav>}</header>
 <main id="workspace" className="hero-main relative z-1 mx-auto grid w-full items-center gap-14 px-6 py-12 lg:grid-cols-[minmax(0,1fr)_300px] lg:px-12 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="hero-copy"><div className="hero-pill inline-flex items-center gap-3 rounded-full px-3 py-2"><span>ResQVoice</span> AI Incident Intelligence</div><h1 className="hero-headline mt-7">Turn live incident conversations into <em>operational intelligence.</em></h1><p className="hero-description mt-7 max-w-[740px]">ResQVoice listens to live incident conversations and continuously structures facts, hypotheses, evidence, decisions, actions, and unresolved questions — giving responders a shared understanding of what is known, what remains uncertain, and what needs attention next.</p><div className="hero-actions mt-8 flex flex-wrap items-center gap-3"><button className="hero-primary px-7 py-4" onClick={onStart}>Start Incident <span aria-hidden="true">&#8599;</span></button><button className="hero-secondary px-7 py-4" onClick={onJoin}>Join Live Room</button><button className="hero-demo px-4 py-4" onClick={onDemo}>Run Demo Incident <span aria-hidden="true">&#8594;</span></button></div><p className="hero-workflow-note mt-4">Start opens the command room. Review and send your incident command there.</p><ul className="hero-capabilities mt-10 flex flex-wrap gap-x-5 gap-y-3" aria-label="Product capabilities">{['LIVE VOICE', 'STRUCTURED CLAIMS', 'EVIDENCE', 'ACTIONS', 'DECISIONS'].map(label => <li key={label}>{label}</li>)}</ul></section>
 <div className="hero-visual-scene hidden lg:block" onPointerMove={e => { if (reduced || !matchMedia('(pointer: fine)').matches)
        return; const rect = e.currentTarget.getBoundingClientRect(), x = (e.clientX - rect.left) / rect.width - .5, y = (e.clientY - rect.top) / rect.height - .5; cancelAnimationFrame(frame.current); frame.current = requestAnimationFrame(() => { visual.current?.style.setProperty('--tilt-x', `${-y * 3}deg`); visual.current?.style.setProperty('--tilt-y', `${x * 4}deg`); }); }} onPointerLeave={() => { cancelAnimationFrame(frame.current); visual.current?.style.setProperty('--tilt-x', '0deg'); visual.current?.style.setProperty('--tilt-y', '0deg'); }}><div ref={visual} className="hero-intelligence-visual"><span className="hero-visual-caption">PRODUCT CONCEPT / NOT LIVE DATA</span><h2>Conversation becomes clarity.</h2><ol>{[['01', 'VOICE', 'The conversation'], ['02', 'CLAIMS', 'Facts and hypotheses'], ['03', 'EVIDENCE', 'Sources and uncertainty'], ['04', 'ACTIONS', 'Operational next steps'], ['05', 'DECISIONS', 'An auditable record']].map(([number, title, description]) => <li key={number}><span>{number}</span><div><strong>{title}</strong><small>{description}</small></div></li>)}</ol><p>One shared incident state.</p></div></div></main>
 <footer className="hero-footer relative z-1 mx-auto flex w-full flex-wrap items-center justify-between gap-4 px-6 pb-6 lg:px-12"><span>{connection === 'Disconnected' ? 'Backend unavailable / you can explore the local demo' : 'Ready for the next incident'}</span><div className="flex items-center gap-5"><span>Voice. Evidence. Accountability.</span>{!reduced && !failed && <button aria-pressed={paused} onClick={() => setPaused(!paused)}>{paused ? 'Play background' : 'Pause background'}</button>}</div></footer></div>;
}
